language: node_js
node_js:
- "0.10"
script: bash ./deploy.sh
env:
  - GH_REF: github.com/juancjara/crop-image/tree/gh-pages/
  - secure: "mDnHENlgnKw9qZR5uLij9IubgColcJGX9Hjsk3rWdjCmxm6PGxXI0rWnJH5q8YB+jSdfCHetq6zAW5ycBcT10aDehJj12erNWJH0gI5GlKkHLInpPS0VnouwG6SBhvKxA0skrtcrBxn3sdeJBFvbMGt96vun8kLSW/4Mpp88FwMDX12xxntJRX9W9MKFDysd14hUKPhLC+SlO7CXOD8cIgtC7YaYofxUDAeSJSAYNY3tvT636Y2ySKMa2VMVOW7d71nBeMyTaf/2Ho2UjIpsMsdF4waxSATXG/p6ScdRKVuA8u+/fdfwTEBRzjRJi3njpJ6pxGUphUdH0Q0JhfD+Z01EBMnQnnsdK0hkA+tKewgGtEP9JqQS7pnQgvMj5WxKL2bfVxKCK1nyNS5PZSNPbUmdVKqhNjEukiJbrzYpFCqtu58L9fYcruoxyaJIByJRYlk2uTpv9z3NBqD89kG/dN5Cm8OAAZcuvsPUQY2KQjjWtDv2flr5Ui48sAK3G3eX6J/XyfvjICXPPJwjCMoY53Yw7t0a9V3Cor7O/7+oU4QeteQGMgXfXMQC5Z/qydLPf6q5BmQvOCfS798w8LYTKPFaYxq24TSGDaOH4IVmj27EGyAijQgTB2HxJt1k/cAsWf0mgGbnNGbkkYwKIuwm5lMpVbZT8915oRwhkb6o5J8="